### ISSUE TITLE
thekmj - Lack of slippage control over NFT IDs can force buyers to buy lesser-valued NFTs than intended, for the same price as the originally intended one.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-beam-auction-judging#30]
thekmj

high

# Lack of slippage control over NFT IDs can force buyers to buy lesser-valued NFTs than intended, for the same price as the originally intended one.

## Summary

The MeritDutchAuction contract is designed to sell sequentially-numbered NFTs, which specifications are defined in the MeritNFT contract. 

However, due to the lack of slippage control over NFT IDs itself, a buyer can, very realistically, be forced to buy a lesser valued NFT than they intended, for the same price.

We also show that, **the optimal buying strategy** for a user, given technical capabilities, **will definitely put another user at risk**.

## Vulnerability Detail

It is natural to think that, in an auction with decaying price, the lower-numbered NFTs are valued higher (e.g. NFT 1 is of more value than NFT 2). It is also natural that in any auction, participants will try to be the one who gets the special item for the lowest price possible.

Suppose a hyped NFT is put on sale. 
- Alice, Bob, Charlie, and Dave, are all looking to be the one who owns the "special" NFT 1.
- As soon as the auction begins, all of them sends a `mint(1)` transaction to buy the coveted NFT. 
- All of their transactions go through, however three of them gets the non-special NFTs **for the same price** as the special one. 

The impact is clear, three of them are forced to buy an NFT that they did not intend to.

Another possible scenario is as follow:
- Eve genuinely wants to buy NFT $N$.
- Eve does not buy it immediately, but rather wait until someone comes and attempts to buy NFT $N$.
   - **Note that this is Eve's optimal buying strategy. She does not intend to grief, but she gets a lower price by waiting due to the price decay.**
- Frank sends a transaction, and attempts to buy NFT $N$.
- Eve front-runs Frank, buying NFT $N$, forcing Frank to get NFT $N+1$.

Using this strategy, Eve was able to buy NFT $N$ at the best possible price. However, Frank is forced to buy NFT $N+1$, which he did not intend to, for the same price as Eve did.
 
## Impact

Due to NFT ID slippage, users may be forced to buy lesser-valued NFTs that they did not intend to, for the same price as the intended one.

## Code Snippet

https://github.com/sherlock-audit/2023-07-beam-auction/blob/main/dutch-nft/src/MeritDutchAuction.sol#L128-L169

## Tool used

Manual Review

## Recommendation

 Add an NFT ID slippage control to `mint()`, reverting if the user does not get the exact NFT they wish for. There are two ways for this:
- Let the user specify the starting NFT to mint as a function parameter.
- Let the user specify the exact NFTs IDs they want to buy.

**Comment by midori-fuse** [comment]
Escalate

This is an ERC721 auction, not an ERC20 auction. NFTs with different IDs are not the same as each other. For said reason, there will be specific IDs that a certain user would want to buy, or a user may not want to buy an NFT if it's numbered too far behind, or they will only want to buy it at a lower price than currently. 

This issue describes a scenario where a user will, given both a real-life scenario, and a scenario where another user acts **optimally but not necessarily malicious** puts another user at risk. An analogy is "you intend to buy the white car, you paid for the white car, but you are forced to get the black car instead".

Even with the "reveal" URI strategy (as per sponsor comment https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/23#issuecomment-1638875903), there is still reason for rational users to hunt for a specific ID (e.g. from purely logical reasoning, or it simply being "the first", or deducing that the NFT will have a favored URI perhaps for being a special number). Additionally, this information was not provided to watsons during the contest, so one has to assume that the users have a clear intention of what they're buying (though one should assume so even with the info).

Furthermore, quoting from the [Sherlock judging criteria](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid):

> **Slippage** related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid **high**

This is also the point of `minAmountOut` parameter in Uniswap pools. Although this is not Uniswap, here the user should be able to specify whether they want the tx to revert and not paying for the wrong item, or if they want to buy that one anyway.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is an ERC721 auction, not an ERC20 auction. NFTs with different IDs are not the same as each other. For said reason, there will be specific IDs that a certain user would want to buy, or a user may not want to buy an NFT if it's numbered too far behind, or they will only want to buy it at a lower price than currently. 
> 
> This issue describes a scenario where a user will, given both a real-life scenario, and a scenario where another user acts **optimally but not necessarily malicious** puts another user at risk. An analogy is "you intend to buy the white car, you paid for the white car, but you are forced to get the black car instead".
> 
> Even with the "reveal" URI strategy (as per sponsor comment https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/23#issuecomment-1638875903), there is still reason for rational users to hunt for a specific ID (e.g. from purely logical reasoning, or it simply being "the first", or deducing that the NFT will have a favored URI perhaps for being a special number). Additionally, this information was not provided to watsons during the contest, so one has to assume that the users have a clear intention of what they're buying (though one should assume so even with the info).
> 
> Furthermore, quoting from the [Sherlock judging criteria](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid):
> 
> > **Slippage** related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid **high**
> 
> This is also the point of `minAmountOut` parameter in Uniswap pools. Although this is not Uniswap, here the user should be able to specify whether they want the tx to revert and not paying for the wrong item, or if they want to buy that one anyway.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jkoppel** [comment]
Interesting argument. When I did the contest, I had been thinking "Nothing can be done about buying the wrong one, so it shouldn't matter,"  but @midori-fuse prevents an alternative design in which it is feasible to run an auction where the choice of NFT matters. Ultimately, only the sponsor can decide if the protocol is meant to support such heterogeneous NFT auctions.

**Comment by midori-fuse** [comment]
Indeed, the point is that NFTs are, by definition, non-fungible, and thus different IDs of the same NFT contract cannot be considered the same token. If tokens are the same, then there is no point to it being an NFT, and user will have no incentive to buy at a price any greater than the lowest price, that is the auction end price.

In a bit more philosophical way to put it, the value of the NFT (or any token) is decided by the users. The ID itself may also place an inherent value in it (not to mention the value created by the URI content).

**Comment by jkoppel** [comment]
I'm not quite sure the implications are true.  Cars are also non-fungible.
If you borrow your friend's 2022 Honda Civic, you better return that exact
vehicle, not another vehicle even if it has the same make, model, color,
etc. But if I'm selling 1000 brand new green Honda Civics with all the same
options, I think it's perfectly fine for me to scoff if you complain you
have the wrong one.

In other words, I  don't think it's clear whether or not the protocol is
intended to support auctions where a buyer may reasonably care about
slippage.

**Comment by Oot2k** [comment]
"In other words, I  don't think it's clear whether or not the protocol is
intended to support auctions where a buyer may reasonably care about
slippage."

I agree with jkoppels last answer, for this reason I still belief this is invalid, but would like to see comments from protocol team and senior watson.
I also think that if the team intends to set the capperaddress to a high value, like mentioned here:

https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/59#issuecomment-1638877492

the value of a certain ID will be low.

**Comment by Czar102** [comment]
In my opinion, the protocol spec only state the number of the NFTs to buy. If the user specified what id do they want to buy and received another, it would be an issue. But that's not the case in the `mint(uint256)` function.

So, in car terms, there are different on the production line and you can buy one, but you can't specify the color. If you try to catch the white one, but improperly count the number of people in the queue before you, or simply don't check the color when paying, it's entirely on you.

Note that using a smart contract, you can select which token would you buy by reading the number of already minted tokens. If you care about the NFT id, you should do that. You can't expect to get the color of the car you want if you don't tell it anyone!

Lastly, the secondary market prices are out of scope for any audit. It's like you reported impermanent loss as loss of funds in an AMM audit because the market price of a pair can change.

edit. Slippage constitutes a loss of funds no matter what the secondary market price is. Here, that's not the case. Hence, I don't think Sherlock's rule about slippage applies here.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
The code is designed to sell all nft's regardless of the id. Considering this a design decision

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [midori-fuse](https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/30/#issuecomment-1647893423): rejected
